### ISSUE TITLE
Configure and test MongoDB database

### ISSUE THREAD

**Issue by clcain** [modulariot/doc#6]
Make sure MongoDB packages are properly installed on modular1 and test adding/removing keys via a Python client.

**Comment by conorpp** [comment]
Chandler is going to get something working.  May not be MongoDB, he will mess around some.

**Comment by clcain** [comment]
MongoDB testing has been moved to VMs.

**Comment by clcain** [comment]
We can now interface with MongoDB via Python, and it appears to be easy. Test code is in the pymongo-test repository.
